# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d02f386675785f629ce7c6ceb56a3ab8912695b5297deac77d9dcff786abcef949e5db55b050d5a2b7939b609777c8b45e6be79356bf1af48fda2a5ef544950

test:
  secret_key_base: 0a5699a6860846bf05305e9d5362e95476d7600ef8a56a188ba9997ae5db99f6234f8cd153460b314d8395749150cb83598406819a8601233e45de099309b7fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
